version: '3.5'

volumes:
  mysql:

services:
#  nginx:
#    image: nginx
#    ports:
#      - '8094:80'
#    networks:
#      - rest-network
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"
    networks:
      - rest-network
    restart: always
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8095:80"
    env_file: .env
    environment:
      - PMA_HOST
    depends_on:
      - mysql
    networks:
      - rest-network
    restart: always
  node-app:
    container_name: app
    build:
      context: .
      target: development
    env_file: .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:debug
    environment:
      - MYSQL_HOST
    depends_on:
      - mysql
    ports:
      - "80:8080"
      - "9229:9229"
    networks:
      - rest-network
    restart: always

networks:
  rest-network:
