version: '3.5'

volumes:
  mysql:

services:
  mysql:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    networks:
      - rest-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8095:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - rest-network
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./app:/usr/src/app
      - ./usr/src/app/node_modules
    command: npm run start:debug
    environment:
      - MYSQL_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    depends_on:
      - mysql
    ports:
      - "80:8080"
    networks:
      - rest-network

networks:
  rest-network:
