version: '3.5'

volumes:
  mysql:

services:
#  nginx:
#    image: nginx
#    ports:
#      - '8094:80'
#    networks:
#      - rest-network
  mysql:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - rest-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8095:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - rest-network
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./app:/usr/src/app
      - ./usr/src/app/node_modules
    command: npm run start:debug
    depends_on:
      - mysql
    ports:
      - "8096:8080"
    networks:
      - rest-network

networks:
  rest-network:
