POST {{ apiHost }}/client
Content-Type: application/json

{
  "firstName": "Иван",
  "lastName": "Иванов",
  "surName": "Иванович",
  "email": "ivanov@mail.ru",
  "vkId": "id123"
}

###

GET {{ apiHost }}/client/2

###

GET {{ apiHost }}/client/1

###

DELETE {{ apiHost }}/client/1

###

PATCH {{ apiHost }}/client/1
Content-Type: application/json

{
  "firstName": "Макс",
  "email": "ivanov@mail.ru"
}
