POST http://localhost:8096/client
Content-Type: application/json

{
  "firstName": "Иван",
  "lastName": "Иванов",
  "surName": "Иванович",
  "email": "ivanov@mail.ru",
  "vkId": "id123"
}

###

GET http://localhost:8096/client

###

GET http://localhost:8096/client/1

###

DELETE http://localhost:8096/client/2

###

PATCH http://localhost:8096/client/1
Content-Type: application/json

{
  "firstName": "Макс",
  "email": "ivanov@mail.ru"
}
